openapi: 3.0.0
info:
  title: Europace Authorization API
  description: TODO
  version: "0.1"
servers:
  - url: https://api.euoprace.de/v1/oauth2
    description: TODO

paths:
  /access-token:
    post:
      summary: TODO
      description: TODO
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Client-Id und Client-Secret müssen per HTTP Basic Auth übergeben werden.
          content:
        - name: grant_type
          in: query
          required: true
          description: |
            OAuth2.0 Grant-Type, muss für den Client-Credentials-Flow client_credentials sein.
        - name: scopes
          in: query
          required: true
          description: |
            " "-separierte Liste von Scopes. Wird ein Subject angegeben muss impersonierung als Scope enthalten sein. Angefragte Scopes werden entsprechend der Rechte des Akteurs und dem Client-Approval durch den Akteur eingeschränkt.
        - name: actor
          in: query
          required: true
          description: |
              Partner-Id des Partners in dessen Auftrag der Client agiert, es muss ein Client-Approval des Akteurs für den Client vorliegen.
        - name: subject
          in: query
          required: true
          description: |
            Partner-Id des Partners in dessen Namen der Client agiert. Das Subject muss dem Akteur untergeordnet sein.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: See http://developers.gettyimages.com/api/docs/v3/oauth2.html
      flows:
        clientCredentials:
          tokenUrl: https://api.gettyimages.com/oauth2/token/
          scopes: {} # Getty Images does not use scopes
