# Diese Datei enthält die Europace2 Oauth2 Konfiguration sowie eine Liste aller Scope-Definitionen. 
#
# Das Format ist
# domäne:ressource:aktion: |
# ## UI Label
# Weiterführende Dokumentation

type: oauth2
description: |
  This API uses OAuth 2 with the client credentials flow. [More info](https://auth0.com/docs/flows/concepts/client-credentials). 
  Der Europace Authorization Server ist erreichbar unter https://api.europace.de/.well-known/oauth-authorization-server."
flows:
  clientCredentials:
    tokenUrl: https://api.europace.de/auth/token
    scopes: # Siehe auch https://swagger.io/specification/ (OAuth Flow Object - Scopes)
      partner:plakette:anlegen: |
        ## Darf neue Plaketten anlegen.
        TODO Beschreibung 
      partner:plakette:loeschen: |
        ## Darf Plaketten löschen
        TODO Beschreibung
      partner:plakette:lesen: |
        ## Darf Partner-Daten lesen
        TODO Beschreibung
      partner:plakette:schreiben: |
        ## Darf Partner-Daten schreiben
        TODO Beschreibung
      partner:beziehungen:lesen: |
        ## Darf Beziehungen zwischen Partnern lesen
        TODO Beschreibung
      partner:beziehungen:schreiben: |
        ## Darf Beziehungen zwischen Partnern schreiben
        TODO Beschreibung
      partner:rechte:lesen: |
        ## Darf Rechte eines Partners lesen
        TODO Beschreibung
      partner:rechte:schreiben: |
        ## Darf Rechte eines Partners schreiben
        TODO Beschreibung

      reporting:rohdaten:lesen: |
        ## Darf im Partnermanagement den Rohdaten-Report runterladen
        TODO Beschreibung
      reporting:produktanbieterreport:lesen: |
        ## Darf im Partnermanagement den produktanbieterreport runterladen
        TODO Beschreibung

      baufinanzierung:echtgeschaeft: |
        ## Baufinanzierung-Echtgeschäft bearbeiten
      baufinanzierung:vorgang:lesen: |
        ## Baufinanzierungsvorgänge lesen
      baufinanzierung:vorgang:schreiben: |
        ## Baufinanzierungsvorgänge schreiben
      baufi-vertrieb:vorgang:anlegen: |
        ## Baufinanzierungsvorgänge anlegen
      baufi-vertrieb:vorgang:loeschen: |
        ## Baufinanzierungsvorgänge löschen
      baufinanzierung:angebot:ermitteln: |
        ## Baufinanzierungsangebote ermitteln
      baufinanzierung:ereignis:lesen: |
        ## Baufinanzierungsereignisse lesen
      baufinanzierung:antrag:lesen: |
        ## Baufinanzierungsanträge lesen
      baufinanzierung:antrag:schreiben: |
        ## Baufinanzierungsanträge schreiben
      baufinanzierung:produktkonfiguration:lesen: |
        ## Produktkonfiguration lesen
      baufinanzierung:produktkonfiguration:schreiben: |
        ## Produktkonfiguration schreiben
      baufinanzierung:produktkonfiguration:freigeben: |
        ## Produktkonfiguration freigeben
      baufinanzierung:produkt:lesen: |
        ## Produkt lesen
      baufinanzierung:produkt:schreiben: |
        ## Produkt schreiben
      baufinanzierung:produktanbieter:lesen: |
        ## Produktanbieter lesen
      baufinanzierung:produktanbieter:schreiben: |
        ## Produktanbieter schreiben

      privatkredit:angebot:ermitteln: |
        ## Kreditsmartangebote ermitteln
      privatkredit:antrag:schreiben: |
        ## Kreditsmartanträge schreiben
      privatkredit:vorgang:lesen: |
        ## Kreditsmartvorgänge lesen
      privatkredit:vorgang:schreiben: |
        ## Kreditsmartvorgänge schreiben

      impersonieren: |
        ## Impersonieren
      openid: |
        ## Benutzer-Login durchführen
      profile: |
        ## Benutzerprofil lesen

    requiredAuthorities:
      baufinanzierung:echtgeschaeft:
        - BS_SICHTBAR
        - ECHTES_GESCHAEFT_ERLAUBT
      baufinanzierung:vorgang:lesen:
        - BS_SICHTBAR
      baufinanzierung:vorgang:schreiben:
        - BS_SICHTBAR
      baufinanzierung:ereignis:lesen:
        - BS_SICHTBAR
      baufinanzierung:antrag:lesen:
        - BS_SICHTBAR
      baufinanzierung:antrag:schreiben:
        - BS_SICHTBAR

      privatkredit:angebot:ermitteln:
        - KREDIT_SMART_SICHTBAR
      privatkredit:antrag:schreiben:
        - KREDIT_SMART_SICHTBAR
      privatkredit:vorgang:lesen:
        - KREDIT_SMART_SICHTBAR
      privatkredit:vorgang:schreiben:
        - KREDIT_SMART_SICHTBAR

      impersonieren:
        - DARF_EINSTELLUNGEN_OEFFNEN
       
